### PR TITLE
Add an `into_inner` method to get inner writer from JsonStreamWriter

### PR DESCRIPTION
**Pull request by Congyuwang**

### CODE REVIEW

**Comment by Marcono1234** [comment]
Out of curiosity, what is the use case where you need the inner writer?

Maybe a bit related to https://github.com/Marcono1234/struson/issues/25; for that feature request the method `JsonStreamReader::reader_mut` was added.

(Also, I will try to close and reopen this merge request, because for whatever reason the GitHub workflow did not run.)

**Comment by Congyuwang** [comment]
Say I have a big json, and a part of it is some really complicated sub-structure that already have `#derive[Deserialize]`. So I want to collect this small part into `Vec<u8>` then just `serde_json`. I would use `JsonStreamWriter::new(Vec::new())`, and store the `JsonStreamWriter` in some state machine, and when finished this sub-objet, use `into_inner` to get the `Vec` data, and `serde_json` it.

I might be able to declare the Vec::new() somewhere else, and then `JsonStreamWriter::new(&mut my_vec)`, but that makes the lifetime issue much more complicated.

**Comment by Marcono1234** [comment]
> The thing is, after I've finished writing, I want to read and reuse the inner buffer. So I need `into_inner` to get the `&mut Vec<u8>` or `Vec<u8>` to read the buffer and `buf.replace()` to put is back for the next reuse.

Rust's `Write` is also implemented for `&mut Write`[^1]. Would it be possible to pass a `&mut` to `JsonStreamWriter` so that you can keep the reference to the buffer?

I am likely not going to add a `JsonStreamWriter::into_inner` method, because it circumvents calling `JsonStreamWriter::finish_document`, and therefore no check is performed that the JSON data is actually complete (and not missing a closing `]` for example) and the buffered data is not flushed to the `Write`.

I have been thinking about adding a return type to `finish_document` though (in the form of an associated type?). In the case of `JsonStreamWriter` that result type could then be the wrapped `Write`. But I haven't tested yet if / how well that works.
Would that help for your use case?

[^1]: Or rather `impl<W: Write + ?Sized> Write for &mut W` and `impl<W: Write + ?Sized> Write for Box<W>`.

**Comment by Congyuwang** [comment]
You are right. I also realized the conflict between `into_inner` and `finish_document`. One way to reconcile the conflict is to change `finish_document` to return `W` after flush. But that would break the API.

It is in my use case rather difficult to use `&mut W` mainly because that I also have to store both the `W` itself and the `JsonStreamWriter<&mut W>` somewhere in the state machine, causing a self-reference issue. Making the JsonWriter owning the W makes things a lot easier for me.

**Comment by Marcono1234** [comment]
In c687a1bde0b8c4f9aad480ec4e0eaab5c9bf13f4 I have added a result type to `finish_document` now. For `JsonStreamWriter` it will be the underlying `Write`. Hopefully that is useful for you. What do you think?

These changes will be part of the upcoming 0.6.0 release, but I am not sure yet when that will happen.

**Comment by Marcono1234** [comment]
Struson version 0.6.0 has now been released, and includes the above mentioned change of adding a result type to `finish_document`.

**Pull request closed without merging**
